import { ApplicationCommandOptionType } from "discord.js";

export default [
    {
        name: "transcribe",
        nameLocalizations: {
            "pt-BR": "transcrever",
        },
        description:
            "Transcribe an audio file! (Works better with english audio)",
        descriptionLocalizations: {
            "pt-BR":
                "Transcreva um arquivo de áudio! (Funciona melhor com áudio em inglês)",
        },
        type: ApplicationCommandOptionType.Subcommand,
        options: [
            // {
            //     name: "file",
            //     nameLocalizations: {
            //         "pt-BR": "arquivo",
            //     },
            //     description:
            //         "The file must be: mp3, mp4, mpeg, mpga, m4a, wav, or webm.",
            //     descriptionLocalizations: {
            //         "pt-BR":
            //             "O arquivo deve ser: mp3, mp4, mpeg, mpga, m4a, wav, ou webm.",
            //     },
            //     type: ApplicationCommandOptionType.Attachment,
            //     required: false,
            // },
            {
                name: "url",
                nameLocalizations: {
                    "pt-BR": "url",
                },
                description: "The url of a video. (Youtube)",
                descriptionLocalizations: {
                    "pt-BR": "A url de um vídeo. (Youtube)",
                },
                type: ApplicationCommandOptionType.String,
                required: true,
            },
            {
                name: "prompting",
                nameLocalizations: {
                    "pt-BR": "prompting",
                },
                description:
                    "You can use a prompt to improve the quality of the transcripts generated by Whisper.",
                descriptionLocalizations: {
                    "pt-BR":
                        "Você pode usar um prompt para melhorar a qualidade das transcrições geradas pelo Whisper.",
                },
                type: ApplicationCommandOptionType.String,
                required: false,
            },
            {
                name: "language",
                nameLocalizations: {
                    "pt-BR": "idioma",
                },
                description:
                    "You can provide a language code to improve the quality. ( ISO-639-1 )",
                descriptionLocalizations: {
                    "pt-BR":
                        "Você pode fornecer um código de idioma para melhorar a qualidade. ( ISO-639-1 )",
                },
                type: ApplicationCommandOptionType.String,
                required: false,
            },
        ],
    },
    {
        name: "translate",
        nameLocalizations: {
            "pt-BR": "traduzir",
        },
        description: "Translate an audio file to english (Only english!)",
        descriptionLocalizations: {
            "pt-BR":
                "Traduza um arquivo de áudio para o inglês (Somente inglês!)",
        },
        type: ApplicationCommandOptionType.Subcommand,
        options: [
            // {
            //     name: "file",
            //     nameLocalizations: {
            //         "pt-BR": "arquivo",
            //     },
            //     description:
            //         "The file must be: mp3, mp4, mpeg, mpga, m4a, wav, or webm.",
            //     descriptionLocalizations: {
            //         "pt-BR":
            //             "O arquivo deve ser: mp3, mp4, mpeg, mpga, m4a, wav, ou webm.",
            //     },
            //     type: ApplicationCommandOptionType.Attachment,
            //     required: false,
            // },
            {
                name: "url",
                nameLocalizations: {
                    "pt-BR": "url",
                },
                description: "The url of a video. (Youtube)",
                descriptionLocalizations: {
                    "pt-BR": "A url de um vídeo. (Youtube)",
                },
                type: ApplicationCommandOptionType.String,
                required: true,
            },
            {
                name: "prompting",
                nameLocalizations: {
                    "pt-BR": "prompting",
                },
                description:
                    "You can use a prompt to improve the quality of the transcripts generated by Whisper.",
                descriptionLocalizations: {
                    "pt-BR":
                        "Você pode usar um prompt para melhorar a qualidade das transcrições geradas pelo Whisper.",
                },
                type: ApplicationCommandOptionType.String,
                required: false,
            },
        ],
    },
    {
        name: "help",
        nameLocalizations: {
            "pt-BR": "ajuda",
        },
        description: "Provides some help for the user.",
        descriptionLocalizations: {
            "pt-BR": "Fornece alguma ajuda para o usuário.",
        },
        type: ApplicationCommandOptionType.SubcommandGroup,
        options: [
            {
                name: "transcribe",
                nameLocalizations: {
                    "pt-BR": "transcrição",
                },
                description: "Provides help for the transcribe command.",
                descriptionLocalizations: {
                    "pt-BR": "Fornece ajuda para o comando de transcrição.",
                },
                type: ApplicationCommandOptionType.Subcommand,
            },
            {
                name: "translate",
                nameLocalizations: {
                    "pt-BR": "tradução",
                },
                description: "Provides help for the translate command.",
                descriptionLocalizations: {
                    "pt-BR": "Fornece ajuda para o comando de tradução.",
                },
                type: ApplicationCommandOptionType.Subcommand,
            }
        ],
    },
];
